# Get all contacts
GET http://localhost:3000/contacts
###
# Get a single contact
GET http://localhost:3000/contacts/682642e1b350de593f83db41
###
# Create a new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Jonah",
  "lastName": "Joe",
  "email": "jonah@notreal.com",
  "favoriteColor": "Orange",
  "birthday": "01/17/98"
}
###
# Update a contact
PUT http://localhost:3000/contacts/682642e1b350de593f83db41
Content-Type: application/json

{
  "firstName": "Sylisa",
  "lastName": "Hall",
  "email": "lilsis@gmail.com",
  "favoriteColor": "Pink",
  "birthday": "05/25/02"
}
###
# Delete a contact
DELETE http://localhost:3000/contacts/6831fe2e7127692acc2230f4

# RENDER LINKS BELOW
# RENDER LINKS BELOW
# RENDER LINKS BELOW
# RENDER LINKS BELOW

# Get all contacts
GET https://cse341-zhyh.onrender.com/contacts
###
# Get a single contact
GET https://cse341-zhyh.onrender.com/contacts/682642e1b350de593f83db41
###
# Create a new contact
POST https://cse341-zhyh.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Jonah",
  "lastName": "Joe",
  "email": "jonah@notreal.com",
  "favoriteColor": "Orange",
  "birthday": "01/17/98"
}
###
# Update a contact
PUT https://cse341-zhyh.onrender.com/contacts/682642e1b350de593f83db41
Content-Type: application/json

{
  "firstName": "Sylisa",
  "lastName": "Hall",
  "email": "lilsis@gmail.com",
  "favoriteColor": "Pink",
  "birthday": "05/25/02"
}
###
# Delete a contact
DELETE https://cse341-zhyh.onrender.com/contacts/6831fe2e7127692acc2230f4